Repository ascendia-network/maga-wallet-mobile, pull requests merged in 2025-04, with the labels that each got.

#2 chore: add GH Actions for linting codebase, run unit tests, label pull requests
  .github/workflows/linter.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/unit-tests.yml
  yarn.lock
Labels: chore

#4 chore: add 'deps' label type for better dependency tracking in PRs
  .github/workflows/pull-request-label.yml
Labels: chore, fix

#3 chore: add GH Actions for linting codebase, run unit tests, label pull requests
  .github/workflows/linter.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/unit-tests.yml
  yarn.lock
Labels: chore, fix, deps

#5 chore: add GH Actions for linting codebase, run unit tests, label pull requests
  .github/workflows/linter.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/unit-tests.yml
  yarn.lock
Labels: chore, fix, deps

#6 chore: update ESLint and Prettier configurations, remove App.tsx, and refactor index.js to import App
  .eslintrc.js
  .github/workflows/pull-request-label.yml
  .prettierrc.js
  __tests__/App.test.tsx
  babel.config.js
  index.js
  jest.config.js
  metro.config.js
  package.json
  src/app/index.tsx
  src/components/index.ts
  src/core/.gitkeep
  src/lib/__tests__/.gitkeep
  src/lib/index.ts
  src/navigation/index.ts
  src/screens/index.ts
  src/utils/__tests__/.gitkeep
  src/utils/index.ts
  tsconfig.json
  yarn.lock
Labels: chore, tests, deps

#8 chore: add pre-commit hook for linting and format code with lint-staged
  .husky/pre-commit
  ios/MAGAWallet.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/MAGAWallet.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  yarn.lock
Labels: chore, config

#7 chore: enhance Babel configuration with module resolver and add font assets for iOS and Android
  android/app/src/main/assets/fonts/Onest-Medium.ttf
  android/app/src/main/assets/fonts/Onest-SemiBold.ttf
  android/link-assets-manifest.json
  babel.config.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet.xcworkspace/contents.xcworkspacedata
  ios/MAGAWallet/Info.plist
  ios/Podfile.lock
  ios/link-assets-manifest.json
  package.json
  react-native.config.js
  src/assets/fonts/Onest-Medium.ttf
  src/assets/fonts/Onest-SemiBold.ttf
  yarn.lock
Labels: chore, performance

#9 feat(ui): add color constants for UI design
  src/constants/ui/colors.ts
Labels: feature

#10 chore(ui): refactor color constants for improved organization and clarity
  src/constants/index.ts
  src/constants/ui/fonts.ts
Labels: chore

#12 feat: add localization
  package.json
  src/localization/i18n.ts
  src/localization/locales/English.json
  yarn.lock
Labels: feature

#11 feat(typography): implement Typography component with customizable styles and unit tests
  jest.config.js
  package.json
  src/components/atoms/typography/__tests__/typography.test.tsx
  src/components/atoms/typography/constants.ts
  src/components/atoms/typography/index.tsx
  src/components/atoms/typography/types.ts
  src/components/index.ts
  yarn.lock
Labels: feature, refactoring, tests

#14 deps: update dependencies in package.json
  android/app/src/main/java/com/magawallet/MainActivity.kt
  ios/Podfile.lock
  jest.config.js
  jest/setup.js
  package.json
  yarn.lock
Labels: chore, feature

#13 ui(ios): add splash logo and background assets
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet/Images.xcassets/Contents.json
  ios/MAGAWallet/Images.xcassets/SplashAppLogo.imageset/Contents.json
  ios/MAGAWallet/Images.xcassets/SplashAppLogo.imageset/Logo Elements 1.svg
  ios/MAGAWallet/Images.xcassets/SplashAppLogo.imageset/Logo Elements 2.svg
  ios/MAGAWallet/Images.xcassets/SplashAppLogo.imageset/Logo Elements.svg
  ios/MAGAWallet/Images.xcassets/SplashBackgroundPrimary.colorset/Contents.json
  ios/MAGAWallet/LaunchScreen.storyboard
Labels: config

#15 feat: add custom button, colors palette
  Gemfile.lock
  ios/Podfile.lock
  src/app/index.tsx
  src/components/atoms/index.ts
  src/components/index.ts
  src/components/molecules/button/index.tsx
  src/components/molecules/button/styles.tsx
  src/components/molecules/index.ts
  src/components/molecules/primary-button/index.tsx
  src/components/molecules/primary-button/styles.ts
  src/components/molecules/secondary-button/index.tsx
  src/components/molecules/secondary-button/styles.ts
  src/constants/ui/colors.ts
  src/utils/__tests__/scaling.test.ts
  src/utils/index.ts
  src/utils/scaling.ts
Labels: feature

#16 feat: implement navigation context and splash screen; add SafeAreaProvider and StatusBar components
  .eslintrc.js
  babel.config.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/app/index.tsx
  src/app/providers/navigation.tsx
  src/app/providers/safe-area.tsx
  src/app/providers/with-providers.tsx
  src/assets/images/auth-initial-background.png
  src/components/atoms/app-icon-container/index.tsx
  src/components/atoms/app-icon-container/styles.ts
  src/components/atoms/index.ts
  src/components/index.ts
  src/components/svgs/app-icon.tsx
  src/components/svgs/index.ts
  src/components/templates/status-bar/index.tsx
  src/constants/index.ts
  src/constants/ui/colors.ts
  src/constants/ui/device.ts
  src/constants/ui/styles.ts
  src/contexts/navigation/index.ts
  src/contexts/navigation/navigation.context.ts
  src/contexts/navigation/types.ts
  src/core/.gitkeep
  src/lib/create-context-selector.tsx
  src/lib/index.ts
  src/navigation/root-stack/root-stack.navigation.tsx
  src/navigation/root-stack/routes.ts
  src/navigation/root-stack/types.ts
  src/screens/auth/index.tsx
  src/screens/auth/styles.ts
  src/screens/index.ts
  src/screens/splash/__tests__/splash-screen.test.tsx
  src/screens/splash/hooks/use-splash-navigation.ts
  src/screens/splash/index.tsx
  src/screens/splash/styles.ts
  src/types/index.ts
  src/types/svgs.ts
  tsconfig.json
  yarn.lock
Labels: feature, tests

#18 feat(components): add Spacer component with unit tests
  src/components/atoms/index.ts
  src/components/atoms/spacer/__tests__/spacer.test.tsx
  src/components/atoms/spacer/index.tsx
Labels: feature

#19 feat: add social authentication icons and methods; update navigation and styles
  src/app/providers/navigation.tsx
  src/components/atoms/index.ts
  src/components/atoms/row-container/index.tsx
  src/components/atoms/typography/__tests__/typography.test.tsx
  src/components/atoms/typography/constants.ts
  src/components/atoms/typography/index.tsx
  src/components/index.ts
  src/components/molecules/index.ts
  src/components/molecules/social-item-circle/index.tsx
  src/components/molecules/social-item-circle/styles.ts
  src/components/organisms/index.ts
  src/components/organisms/social-auth-list/index.tsx
  src/components/organisms/social-auth-list/styles.ts
  src/components/svgs/index.ts
  src/components/svgs/socials/apple.tsx
  src/components/svgs/socials/facebook.tsx
  src/components/svgs/socials/google.tsx
  src/components/svgs/socials/x.tsx
  src/components/templates/index.ts
  src/constants/auth/index.ts
  src/constants/auth/methods.ts
  src/constants/ui/colors.ts
  src/constants/ui/device.ts
  src/constants/ui/fonts.ts
  src/navigation/root-stack/index.ts
  src/navigation/root-stack/routes.ts
  src/screens/auth/index.tsx
  src/screens/auth/styles.ts
  src/screens/splash/hooks/use-splash-navigation.ts
Labels: feature, fix

#20 feat: implement localization context and setup passkey screen; add MMKV storage integration
  .eslintrc.js
  Gemfile.lock
  babel.config.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/app/providers/localization.tsx
  src/app/providers/with-providers.tsx
  src/assets/images/passkey-background.png
  src/components/molecules/social-item-circle/index.tsx
  src/components/organisms/social-auth-list/index.tsx
  src/constants/ui/fonts.ts
  src/contexts/localization/index.ts
  src/contexts/localization/localization.context.ts
  src/contexts/localization/types.ts
  src/lib/index.ts
  src/lib/mmkv/index.ts
  src/lib/mmkv/keys.ts
  src/lib/mmkv/mmkv.instance.ts
  src/localization/locales/English.json
  src/navigation/root-stack/root-stack.navigation.tsx
  src/navigation/root-stack/routes.ts
  src/navigation/root-stack/types.ts
  src/screens/auth/index.tsx
  src/screens/index.ts
  src/screens/setup-passkey/index.tsx
  src/screens/setup-passkey/styles.ts
  src/types/index.ts
  src/types/localization.ts
  src/utils/index.ts
  src/utils/localization.ts
  tsconfig.json
  yarn.lock
Labels: BREAKING CHANGE, feature, performance

#21 feat: add tabs navigations routes
  ios/Podfile.lock
  package.json
  react-native.config.js
  src/lib/hooks/index.ts
  src/lib/hooks/use-keyboard-height.ts
  src/lib/index.ts
  src/navigation/index.ts
  src/navigation/root-stack/root-stack.navigation.tsx
  src/navigation/root-stack/routes.ts
  src/navigation/root-stack/types.ts
  src/navigation/tabs-stacks/routes.ts
  src/navigation/tabs-stacks/tabs-navigator.tsx
  src/navigation/tabs-stacks/types.ts
  src/navigation/tabs/discover/discover-stack.tsx
  src/navigation/tabs/discover/discover-tab.model.ts
  src/navigation/tabs/home/home-stack.tsx
  src/navigation/tabs/home/home-tab.model.ts
  src/navigation/tabs/index.ts
  src/navigation/tabs/settings/setting-stack.tsx
  src/navigation/tabs/settings/settings-tab.model.ts
  src/screens/discover/discover-screen/index.tsx
  src/screens/discover/discover-screen/styles.ts
  src/screens/discover/index.ts
  src/screens/home/home-screen/index.tsx
  src/screens/home/home-screen/styles.ts
  src/screens/home/index.ts
  src/screens/index.ts
  src/screens/settings/index.ts
  src/screens/settings/settings-screen/index.tsx
  src/screens/settings/settings-screen/styles.ts
  tsconfig.json
  yarn.lock
Labels: feature, fix

#22 feat(onboarding): Implement core layouts & biometrics configs to handle onboarding process
  android/app/src/main/AndroidManifest.xml
  babel.config.js
  ios/MAGAWallet/Info.plist
  ios/Podfile.lock
  jest.config.js
  jest/setup.js
  metro.config.js
  package.json
  src/assets/images/create-wallet-background.png
  src/components/atoms/icon-container/index.tsx
  src/components/atoms/icon-container/styles.ts
  src/components/atoms/index.ts
  src/components/molecules/index.ts
  src/components/molecules/primary-button/__tests__/primary-button.test.tsx
  src/components/molecules/primary-button/index.tsx
  src/components/molecules/secondary-button/index.tsx
  src/components/molecules/setup-faceid-button/index.tsx
  src/components/molecules/setup-passkey-row-item/index.tsx
  src/components/molecules/setup-passkey-row-item/styles.ts
  src/components/organisms/bottom-sheet/index.tsx
  src/components/organisms/bottom-sheet/styles.ts
  src/components/organisms/index.ts
  src/components/organisms/setup-passkey-benefits-container/index.tsx
  src/components/svgs/fingerprint.tsx
  src/components/svgs/index.ts
  src/components/svgs/shield.tsx
  src/components/svgs/warning.tsx
  src/components/templates/bottom-sheet-setup-biometrics/index.tsx
  src/components/templates/bottom-sheet-setup-biometrics/styles.ts
  src/components/templates/index.ts
  src/constants/ui/device.ts
  src/constants/ui/fonts.ts
  src/core/biometrics/lib/hooks/index.ts
  src/core/biometrics/lib/hooks/use-biometrics.ts
  src/core/biometrics/lib/index.ts
  src/lib/hooks/index.ts
  src/lib/hooks/use-animated-dots.tsx
  src/lib/hooks/use-forwarded-ref.ts
  src/localization/locales/English.json
  src/navigation/root-stack/root-stack.navigation.tsx
  src/navigation/root-stack/routes.ts
  src/navigation/root-stack/types.ts
  src/navigation/tabs-stacks/index.ts
  src/screens/auth/index.tsx
  src/screens/create-wallet-loading/index.tsx
  src/screens/create-wallet-loading/styles.ts
  src/screens/index.ts
  src/screens/setup-passkey/index.tsx
  src/screens/setup-passkey/styles.ts
  yarn.lock
Labels: chore, feature, refactoring, deps

#25 fix(localization): correct formatting in English.json and improve tab…
  src/localization/locales/English.json
  src/navigation/components/tab-bar/index.tsx
Labels: fix

#24 Add bottom menu
  index.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  src/app/providers/navigation.tsx
  src/components/svgs/index.ts
  src/components/svgs/tabs/discover.tsx
  src/components/svgs/tabs/home.tsx
  src/components/svgs/tabs/settings.tsx
  src/localization/locales/English.json
  src/navigation/components/index.ts
  src/navigation/components/tab-bar/index.tsx
  src/navigation/components/tab-bar/styles.ts
  src/navigation/constants.tsx
  src/navigation/tabs-stacks/tabs-navigator.tsx
  src/navigation/tabs-stacks/types.ts
  src/screens/auth/index.tsx
  src/utils/index.ts
  src/utils/navigation.tsx
  yarn.lock
Labels: feature, fix

#26 chore!: update project configuration and dependencies
  .gitignore
  babel.config.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet/Info.plist
  ios/MAGAWallet/MAGAWallet.entitlements
  ios/Podfile.lock
  jest.config.js
  jest/setup.js
  package.json
  src/components/organisms/social-auth-list/index.tsx
  src/constants/common.ts
  src/constants/index.ts
  src/core/auth/constants/index.ts
  src/core/auth/lib/hooks/index.ts
  src/core/auth/lib/hooks/use-twitter-auth.ts
  src/core/auth/lib/index.ts
  yarn.lock
Labels: enhancement, BREAKING CHANGE, chore, feature, deps

#28 chore: update jest configuration and setup
  jest.config.js
  jest/setup.js
Labels: chore

#31 feat(auth!): update project configuration and add Firebase dependencies
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/gradle.properties
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet/AppDelegate.swift
  ios/MAGAWallet/Info.plist
  ios/MAGAWallet/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  jest.config.js
  package.json
  src/components/organisms/social-auth-list/__tests__/social-auth-list.test.tsx
  src/components/organisms/social-auth-list/index.tsx
  src/constants/auth/methods.ts
  src/core/auth/lib/hooks/index.ts
  src/core/auth/lib/hooks/use-auth.ts
  src/core/auth/lib/hooks/use-twitter-middleware.ts
  src/navigation/tabs-stacks/tabs-navigator.tsx
  src/navigation/tabs/discover/discover-stack.tsx
  src/navigation/tabs/home/home-stack.tsx
  src/navigation/tabs/settings/setting-stack.tsx
  src/types/auth.ts
  src/types/index.ts
  yarn.lock
Labels: config, feature, fix, tests

#30 feat: passcode screens
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/components/molecules/index.ts
  src/components/molecules/passcode-indicator/index.tsx
  src/components/molecules/passcode-indicator/styles.ts
  src/components/organisms/index.ts
  src/components/organisms/keyboard/index.tsx
  src/components/organisms/keyboard/styles.tsx
  src/lib/keychain/index.ts
  src/lib/keychain/keychain.instance.ts
  src/lib/keychain/keys.ts
  src/lib/mmkv/keys.ts
  src/localization/locales/English.json
  src/navigation/root-stack/types.ts
  src/navigation/tabs/settings/setting-stack.tsx
  src/navigation/tabs/settings/settings-tab.model.ts
  src/screens/auth/index.tsx
  src/screens/passcode/confirm-new-passcode/index.tsx
  src/screens/passcode/create-new-passcode/index.tsx
  src/screens/passcode/enter-passcode/index.tsx
  src/screens/passcode/hooks/index.ts
  src/screens/passcode/hooks/use-handle-code-change.ts
  src/screens/passcode/hooks/use-handle-remove.ts
  src/screens/passcode/hooks/use-shake-animation.ts
  src/screens/passcode/index.ts
  src/screens/passcode/passcode-layout/index.tsx
  src/screens/passcode/passcode-layout/styles.ts
  src/utils/__tests__/delay.test.ts
  src/utils/__tests__/string-utils.test.ts
  src/utils/delay.ts
  src/utils/index.ts
  src/utils/string.ts
  yarn.lock
Labels: BREAKING CHANGE, feature, fix

#32 deps: add react-native-passkey
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: deps

#34 feat(auth): enhance authentication flow and add new dependencies
  .github/workflows/linter.yml
  .github/workflows/unit-tests.yml
  __mocks__/@react-native-async-storage/async-storage.js
  android/app/src/main/AndroidManifest.xml
  globals.js
  index.js
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet/MAGAWallet.entitlements
  ios/Podfile.lock
  jest.config.js
  jest/setup.js
  metro.config.js
  package.json
  src/constants/config.ts
  src/constants/crypto/index.ts
  src/constants/crypto/networks.ts
  src/constants/index.ts
  src/core/auth/api/index.ts
  src/core/auth/api/x/index.ts
  src/core/auth/api/x/types.ts
  src/core/auth/api/x/x.api.ts
  src/core/auth/constants/index.ts
  src/core/auth/lib/hooks/use-auth.ts
  src/core/auth/lib/hooks/use-twitter-middleware.ts
  src/core/biometrics/lib/passkey.ts
  src/lib/crypto/index.ts
  src/lib/crypto/rpc-provider.ts
  src/lib/index.ts
  src/lib/web3auth/config.ts
  src/lib/web3auth/decode.ts
  src/lib/web3auth/index.ts
  src/lib/web3auth/instance.ts
  src/lib/web3auth/types.ts
  src/types/index.ts
  src/types/networks.ts
  yarn.lock
Labels: chore, feature
