Repository ascendia-network/maga-wallet-mobile, pull requests merged in 2025-05, with the labels that each got.

#36 feat(auth): add Twitter authentication support and update environment configurations
  .env.example
  .gitignore
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest.config.js
  jest/setup.js
  package.json
  src/components/atoms/index.ts
  src/components/atoms/safe-view-container/__tests__/safe-view-container.test.tsx
  src/components/atoms/safe-view-container/index.tsx
  src/components/molecules/index.ts
  src/components/molecules/setup-biometrics-button/index.tsx
  src/components/molecules/social-item-circle/index.tsx
  src/components/organisms/social-auth-list/index.tsx
  src/components/templates/bottom-sheet-setup-biometrics/index.tsx
  src/constants/common.ts
  src/core/auth/api/x/x.api.ts
  src/core/auth/lib/hooks/use-auth.ts
  src/core/auth/lib/hooks/use-twitter-middleware.ts
  src/core/auth/utils/index.ts
  src/core/auth/utils/linking.ts
  src/lib/web3auth/config.ts
  src/navigation/components/tab-bar/index.tsx
  src/screens/auth/index.tsx
  src/screens/setup-passkey/index.tsx
  src/utils/delay.ts
  yarn.lock
Labels: feature, refactoring, tests

#37 feat(account-actions): add AccountActionPressableContainer and related icons for send, swap, and receive actions
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/MAGAWallet/MAGAWallet.entitlements
  package.json
  src/components/atoms/account-action-pressable-container/index.tsx
  src/components/atoms/account-action-pressable-container/styles.ts
  src/components/atoms/index.ts
  src/components/index.ts
  src/components/molecules/account-actions-container/index.tsx
  src/components/molecules/index.ts
  src/components/molecules/setup-biometrics-button/index.tsx
  src/components/svgs/index.ts
  src/components/svgs/receive.tsx
  src/components/svgs/send.tsx
  src/components/svgs/swap.tsx
  src/constants/config.ts
  src/core/auth/lib/biometrics/index.ts
  src/core/auth/lib/biometrics/passkey.ts
  src/core/auth/lib/hooks/index.ts
  src/core/auth/lib/hooks/use-biometrics.ts
  src/core/biometrics/lib/hooks/index.ts
  src/core/biometrics/lib/index.ts
  src/screens/home/home-screen/index.tsx
  src/screens/home/home-screen/styles.ts
  yarn.lock
Labels: feature, refactoring

#39 fix: fix ios build issues
  ios/MAGAWallet.xcodeproj/project.pbxproj
  ios/Podfile.lock
Labels: fix

#40 feat(history, settings): add History tab and refactor Settings screens tabs
  src/components/atoms/index.ts
  src/components/atoms/settings-menu-item/index.tsx
  src/components/atoms/settings-menu-item/styles.ts
  src/components/molecules/secondary-button/__test__/secondary-button.test.tsx
  src/components/svgs/index.ts
  src/components/svgs/tabs/history.tsx
  src/localization/locales/English.json
  src/navigation/components/index.ts
  src/navigation/components/tab-bar/index.tsx
  src/navigation/constants.tsx
  src/navigation/root-stack/types.ts
  src/navigation/tabs-stacks/routes.ts
  src/navigation/tabs-stacks/tabs-navigator.tsx
  src/navigation/tabs-stacks/types.ts
  src/navigation/tabs/history/history-stack.tsx
  src/navigation/tabs/history/history-tab.model.ts
  src/navigation/tabs/index.ts
  src/navigation/tabs/settings/setting-stack.tsx
  src/screens/history/history-screen/index.tsx
  src/screens/history/history-screen/styles.ts
  src/screens/history/index.ts
  src/screens/index.ts
  src/screens/passcode/enter-passcode/index.tsx
  src/screens/settings/index.ts
  src/screens/settings/screens/about/index.tsx
  src/screens/settings/screens/about/styles.ts
  src/screens/settings/screens/address-book/index.tsx
  src/screens/settings/screens/address-book/styles.ts
  src/screens/settings/screens/manage-accounts/index.tsx
  src/screens/settings/screens/manage-accounts/styles.ts
  src/screens/settings/screens/notifications/index.tsx
  src/screens/settings/screens/notifications/styles.ts
  src/screens/settings/screens/preferences/index.tsx
  src/screens/settings/screens/preferences/styles.ts
  src/screens/settings/screens/security/components/index.ts
  src/screens/settings/screens/security/components/security-toggle/index.tsx
  src/screens/settings/screens/security/constants/index.ts
  src/screens/settings/screens/security/hooks/index.ts
  src/screens/settings/screens/security/index.tsx
  src/screens/settings/screens/security/styles.ts
  src/screens/settings/screens/security/types.ts
  src/screens/settings/screens/settings-main-screen/index.tsx
  src/screens/settings/screens/settings-main-screen/styles.ts
  src/screens/two-fa-auth/two-fa-setup/index.tsx
  src/utils/navigation.tsx
Labels: fix, refactoring

#45 feat: implement DEX tx status screens & re-fetch price on liquidity pools volume change
  src/assets/images/tx-failed-background.png
  src/assets/images/tx-success-background.png
  src/components/svgs/failed-icon-wrapped.tsx
  src/components/svgs/index.ts
  src/core/dex/components/atoms/swap-review-token-item/index.tsx
  src/core/dex/components/organisms/review-swap-button/index.tsx
  src/core/dex/components/organisms/submit-swap-actions/index.tsx
  src/core/dex/components/organisms/swap-trade-details/index.tsx
  src/core/dex/components/templates/index.ts
  src/core/dex/components/templates/tx-status-buttons/index.tsx
  src/core/dex/components/templates/tx-status-buttons/styles.ts
  src/core/dex/context/swap.context.tsx
  src/core/dex/lib/abi/PAIR.ts
  src/core/dex/lib/hooks/index.ts
  src/core/dex/lib/hooks/use-all-liquidity-pools.ts
  src/core/dex/lib/hooks/use-trade-price-listener.ts
  src/localization/locales/English.json
  src/navigation/tabs/home/home-stack.tsx
  src/navigation/tabs/home/types.ts
  src/screens/auth/index.tsx
  src/screens/auth/styles.ts
  src/screens/create-wallet-loading/index.tsx
  src/screens/create-wallet-loading/styles.ts
  src/screens/dex/index.tsx
  src/screens/dex/screens/index.ts
  src/screens/dex/screens/success/index.tsx
  src/screens/dex/screens/tx-status/index.tsx
  src/screens/dex/screens/tx-status/styles.ts
  src/screens/setup-passkey/index.tsx
  src/screens/setup-passkey/styles.ts
  src/screens/splash/hooks/use-splash-navigation.ts
Labels: feature, refactoring

#46 feat: add base send feature ui layout
  src/components/animated/index.ts
  src/components/animated/send-funds-animated-amount/index.tsx
  src/components/animated/send-funds-animated-amount/styles.ts
  src/components/atoms/bottom-sheet-token-item/index.tsx
  src/components/atoms/bottom-sheet-token-item/styles.ts
  src/components/atoms/index.ts
  src/components/molecules/account-actions-container/index.tsx
  src/components/molecules/index.ts
  src/components/molecules/send-funds-token-selector/index.tsx
  src/components/molecules/send-funds-token-selector/styles.ts
  src/components/organisms/keyboard/index.tsx
  src/components/svgs/arrow.tsx
  src/components/templates/bottom-sheets/index.ts
  src/components/templates/bottom-sheets/select-wallet/index.tsx
  src/components/templates/bottom-sheets/tokens-list/index.tsx
  src/constants/ui/index.ts
  src/constants/ui/keyboard.presets.ts
  src/core/dex/components/templates/bottom-sheet-tokens-list/index.tsx
  src/core/send-funds/lib/hooks/index.ts
  src/core/send-funds/lib/hooks/use-keyboard-handler.ts
  src/core/send-funds/lib/index.ts
  src/core/send-funds/model/index.ts
  src/core/send-funds/model/send-funds.store.ts
  src/core/send-funds/model/types.ts
  src/navigation/tabs/home/home-stack.tsx
  src/navigation/tabs/home/types.ts
  src/screens/index.ts
  src/screens/send-funds/index.tsx
  src/screens/send-funds/screens/index.ts
  src/screens/send-funds/styles.ts
  src/screens/splash/hooks/use-splash-navigation.ts
Labels: feature, refactoring
